### ISSUE TITLE
Make a program asks for a sequence and detects if it is a sequence of DNA, RNA or a protein.

### ISSUE THREAD

**Issue by FRedMCR** [swarris/pyPaSWAS#5]
Hi, i'm trying to make a program that reciving a sequence can say if that is from DNA, RNA or Protein.
I tried this:
`seq = input('Enter a seq')`
`DNA=['A','C','G','T']`
`RNA=['A','C','G','U']`
`AA=['Q','W','E','R','Y','I','P','S','D','F','H','K','L','V','N','M']`
`for item in seq:`
`    if item in DNA: `
      
![sin titulo](https://user-images.githubusercontent.com/34608189/38176365-bdb49aae-35ed-11e8-90b6-2baeae0c47b0.png)
 ` print('DNA')`
   ` elif 'U' in seq:`
       ` print('RNA')`
  `  elif item in AA:`
       ` print('aminoacid')`
    `else:`
        `print('no idea')`
        `print('no idea')`

However it print for each position if it belongs to dna, rna or protein but i only want that this programe evaluate every position and then print the result.

**Comment by swarris** [comment]
I would recommend to use biopython for these kinds of things: http://biopython.org/wiki/SeqIO
